[phases.setup]
nixPkgs = ['jdk17']

[phases.install]
cmds = ['curl -s "https://get.sdkman.io" | bash', 'source "$HOME/.sdkman/bin/sdkman-init.sh"', 'sdk install maven']

[phases.build]
cmds = ['./mvnw clean package -DskipTests || mvn clean package -DskipTests']

[start]
cmd = 'java -Dserver.port=$PORT -jar target/resource-labor-forecast-1.0.0.jar'